import '../models/workout_session.dart';

class ExerciseMeta {
  final String name;
  final MuscleGroup group;
  final String difficulty;
  final String equipment;
  final String category;
  final List<String> tips;
  final List<String> targetMuscles;
  final List<String> cues;
  final String imageAsset;
  final String muscleAsset;
  final String? videoUrl;

  const ExerciseMeta({
    required this.name,
    required this.group,
    required this.difficulty,
    required this.equipment,
    required this.category,
    required this.tips,
    required this.targetMuscles,
    required this.cues,
    required this.imageAsset,
    required this.muscleAsset,
    this.videoUrl,
  });
}

class ExerciseLibrary {
  static final List<ExerciseMeta> exercises = [
    ExerciseMeta(
      name: '平板卧推',
      group: MuscleGroup.chest,
      difficulty: '中级',
      equipment: '杠铃',
      category: '复合动作',
      tips: [
      '下放时吸气，上推时呼气',
      '控制节奏，不要弹杠',
      '握距与肩同宽或略宽',
      ],
      targetMuscles: [
      '胸肌',
      '三角肌前束',
      '肱三头肌',
      ],
      cues: [
      '挺胸收肩胛骨',
      '杠铃路径垂直上下',
      '手腕保持中立',
      ],
      imageAsset: 'assets/exercises/bench_press.gif',
      muscleAsset: 'assets/muscles/bench_press.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-barbell-bench-press-side.mp4',
    ),
    ExerciseMeta(
      name: '上斜卧推',
      group: MuscleGroup.chest,
      difficulty: '中级',
      equipment: '哑铃',
      category: '复合动作',
      tips: [
      '凳子角度30-45度最佳',
      '握距比肩宽略宽',
      '手腕保持中立',
      ],
      targetMuscles: [
      '上胸',
      '三角肌前束',
      '肱三头肌',
      ],
      cues: [
      '感受上胸发力',
      '哑铃向中线靠拢',
      '控制回落速度',
      ],
      imageAsset: 'assets/exercises/incline_bench_press.gif',
      muscleAsset: 'assets/muscles/incline_bench_press.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-dumbbell-incline-bench-press-side_cQCX9or.mp4',
    ),
    ExerciseMeta(
      name: '下斜卧推',
      group: MuscleGroup.chest,
      difficulty: '中级',
      equipment: '杠铃',
      category: '复合动作',
      tips: [
      '下斜角度不超过20度',
      '头部低于身体',
      '量力而行',
      ],
      targetMuscles: [
      '下胸',
      '三角肌前束',
      '肱三头肌',
      ],
      cues: [
      '集中下胸发力',
      '控制动作幅度',
      '呼吸配合',
      ],
      imageAsset: 'assets/exercises/incline_bench_press.gif',
      muscleAsset: 'assets/muscles/incline_bench_press.png',
    ),
    ExerciseMeta(
      name: '哑铃飞鸟',
      group: MuscleGroup.chest,
      difficulty: '初级',
      equipment: '哑铃',
      category: '孤立动作',
      tips: [
      '手臂微屈保护关节',
      '集中感受胸肌拉伸',
      '不要使用过大重量',
      ],
      targetMuscles: [
      '胸肌',
      '三角肌前束',
      ],
      cues: [
      '打开时充分拉伸',
      '合拢时顶峰收缩',
      '控制速度',
      ],
      imageAsset: 'assets/exercises/pec_deck.gif',
      muscleAsset: 'assets/muscles/dumbbell_fly.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Machine-machine-pec-fly-side.mp4',
    ),
    ExerciseMeta(
      name: '俯卧撑',
      group: MuscleGroup.chest,
      difficulty: '初级',
      equipment: '自重',
      category: '复合动作',
      tips: [
      '身体保持一条直线',
      '下放到胸部接近地面',
      '手掌略宽于肩',
      ],
      targetMuscles: [
      '胸肌',
      '三角肌前束',
      '肱三头肌',
      '核心',
      ],
      cues: [
      '核心收紧',
      '肘部呈45度外展',
      '下去时吸气上来时呼气',
      ],
      imageAsset: 'assets/exercises/push_up.gif',
      muscleAsset: 'assets/muscles/push_up.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Bodyweight-push-up-side.mp4',
    ),
    ExerciseMeta(
      name: '蝴蝶机夹胸',
      group: MuscleGroup.chest,
      difficulty: '初级',
      equipment: '器械',
      category: '孤立动作',
      tips: [
      '手肘微屈不要锁死',
      '发力时呼气',
      '手柄高度与肩同宽',
      ],
      targetMuscles: [
      '胸肌',
      '三角肌前束',
      ],
      cues: [
      '挺胸夹紧肩胛骨',
      '双手靠拢时感受胸肌挤压',
      '控制离心阶段',
      ],
      imageAsset: 'assets/exercises/pec_deck.gif',
      muscleAsset: 'assets/muscles/pec_fly.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Machine-machine-pec-fly-side.mp4',
    ),
    ExerciseMeta(
      name: '绳索夹胸',
      group: MuscleGroup.chest,
      difficulty: '初级',
      equipment: '绳索',
      category: '孤立动作',
      tips: [
      '手柄位置与肩同高',
      '交叉时保持张力',
      '单侧做完换另一侧',
      ],
      targetMuscles: [
      '胸肌',
      '三角肌前束',
      ],
      cues: [
      '手臂微屈',
      '感受胸肌拉伸和收缩',
      '不要借助身体力量',
      ],
      imageAsset: 'assets/exercises/lateral_raise.gif',
      muscleAsset: 'assets/muscles/lateral_raise.png',
    ),
    ExerciseMeta(
      name: '单臂哑铃划船',
      group: MuscleGroup.back,
      difficulty: '中级',
      equipment: '哑铃',
      category: '复合动作',
      tips: ['垂直上下移动', '顶峰收缩夹紧肩胛骨', '不要塌腰'],
      targetMuscles: ['背阔肌', '斜方肌', '菱形肌'],
      cues: ['用非发力臂撑在稳固物体上（如长凳、箱子）。采取错步站姿，使与发力臂同侧的腿站在后方。', '尽量让上身与地面平行。这样可以扩大你的活动范围', '让手臂自然下垂，然后把肘部向后拉。想象腋下夹着一个网球，每次都把它夹紧。'],
      imageAsset: 'assets/exercises/one_arm_row.gif',
      muscleAsset: 'assets/muscles/one_arm_row.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Dumbbells-dumbbell-row-unilateral-side.mp4',
    ),
    ExerciseMeta(
      name: '高位下拉',
      group: MuscleGroup.back,
      difficulty: '初级',
      equipment: '器械',
      category: '复合动作',
      tips: ['挺胸收腹', '肘垂直向下移动', '感受背阔肌拉伸'],
      targetMuscles: ['背阔肌', '斜方肌', '肱二头肌'],
      cues: ['将上身向后倾约30度，同时挺胸。', '以平稳的动作把杆拉到大约下巴高度或略低，同时收紧肩胛骨。', '不要过度后仰'],
      imageAsset: 'assets/exercises/lat_pulldown.gif',
      muscleAsset: 'assets/muscles/lat_pulldown.png',
       videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-machine-pulldown-side.mp4',
    ),
    ExerciseMeta(
      name: '坐姿划船',
      group: MuscleGroup.back,
      difficulty: '中级',
      equipment: '器械/缆索',
      category: '复合动作',
      tips: ['握距与肩同宽', '向后拉时夹紧肩胛骨', '胸部贴近器械'],
      targetMuscles: ['背阔肌', '斜方肌中束', '菱形肌'],
      cues: ['向后拉手肘不要张开', '感受背肌挤压', '控制还原速度'],
      imageAsset: 'assets/exercises/seated_row.gif',
      muscleAsset: 'assets/muscles/seated_row.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-machine-seated-cable-row-side.mp4',
    ),
    ExerciseMeta(
      name: '杠铃俯身划船',
      group: MuscleGroup.back,
      difficulty: '中级',
      equipment: '杠铃',
      category: '复合动作',
      tips: ['俯身约45度', '哑铃垂直上下移动', '背部平直不弓背'],
      targetMuscles: ['背阔肌', '斜方肌', '菱形肌'],
      cues: ['掌心朝下握住杠铃。臀部向后推并前倾，保持背部平直，直到躯干与地面大致平行。', '把杠拉向躯干，同时肘部微微内收。', '在开始下一次重复前，将肘部完全伸直。'],
      imageAsset: 'assets/exercises/seated_row.gif',
      muscleAsset: 'assets/muscles/bent_over_row.png',
      videoUrl:'https://media.musclewiki.com/media/uploads/videos/branded/female-barbell-pronated-row-side.mp4',
    ),
    ExerciseMeta(
      name: '辅助引体向上',
      group: MuscleGroup.back,
      difficulty: '初级',
      equipment: '器械',
      category: '复合动作',
      tips: ['借助器械减轻体重', '下放时充分伸展背阔肌', '动作要有控制'],
      targetMuscles: ['背阔肌', '斜方肌', '肱二头肌'],
      cues: ['调节辅助重量。站在平台上，双手握住略宽于肩宽的手柄。如有膝垫，将膝盖放在垫上。', '缓慢拉起，直到下巴高过横杆。肘部靠近身体，核心收紧。', '挺胸收紧肩胛骨，感受背肌发力'],
      imageAsset: 'assets/exercises/assisted_pull_up.gif',
      muscleAsset: 'assets/muscles/assisted_pull_up.png',
      videoUrl:'https://media.musclewiki.com/media/uploads/videos/branded/female-Machine-machine-assisted-pull-up-front.mp4',
    ),
    ExerciseMeta(
      name: '绳索直杆下拉',
      group: MuscleGroup.back,
      difficulty: '初级',
      equipment: '绳索',
      category: '复合动作',
      tips: ['向外向后拉', '大拇指朝上', '肩胛骨向中间夹'],
      targetMuscles: ['三角肌后束', '斜方肌', '小圆肌'],
      cues: ['握住手柄，后退几步。把臀部向后推，使上身略微前倾', '用肩部带动动作，不要用肘部。到最底部时，想象将把手从大腿间拉过。'],
      imageAsset: 'assets/exercises/face_pull.gif',
      muscleAsset: 'assets/muscles/face_pull.png',
      videoUrl:'https://media.musclewiki.com/media/uploads/videos/branded/female-Cables-cable-pullover-side.mp4',
    ),
    ExerciseMeta(
      name: '山羊挺身',
      group: MuscleGroup.back,
      difficulty: '中级',
      equipment: '器械',
      category: '孤立动作',
      tips: ['身体呈一条直线', '臀部收紧发力', '动作要缓慢控制', '背部保持平直'],
      targetMuscles: ['竖脊肌', '臀肌', '腘绳肌'],
      cues: ['将大腿放在衬垫上，双脚勾在平台支架上。', '保持背部挺直，缓慢从腰部弯曲，直到腿和背呈45°角。', '动作要缓慢控制'],
      imageAsset: 'assets/exercises/back_extension.gif',
      muscleAsset: 'assets/muscles/back_extension.png',
      videoUrl:'https://media.musclewiki.com/media/uploads/videos/branded/female-Machine-machine-45-degree-back-extension-side.mp4',
    ),
    ExerciseMeta(
      name: '哑铃肩推',
      group: MuscleGroup.shoulders,
      difficulty: '中级',
      equipment: '哑铃',
      category: '复合动作',
      tips: [
      '手臂呈90度角',
      '推至顶点手臂不完全伸直',
      '核心收紧',
      ],
      targetMuscles: [
      '三角肌前束',
      '三角肌中束',
      '肱三头肌',
      ],
      cues: [
      '哑铃垂直上下移动',
      '核心收紧稳定身体',
      '控制速度',
      ],
      imageAsset: 'assets/exercises/arnold_press.gif',
      muscleAsset: 'assets/muscles/dumbbell_shoulder_press.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Vitruvian-overhead-press-side.mp4',
    ),
    ExerciseMeta(
      name: '阿诺德推举',
      group: MuscleGroup.shoulders,
      difficulty: '中级',
      equipment: '哑铃',
      category: '复合动作',
      tips: [
      '动作要连贯流畅',
      '旋转时控制重量',
      '手腕保持中立',
      ],
      targetMuscles: [
      '三角肌前束',
      '三角肌中束',
      '三角肌后束',
      '肱三头肌',
      ],
      cues: [
      '从掌心朝脸开始',
      '推起时旋转掌心朝外',
      '顶峰手伸直',
      ],
      imageAsset: 'assets/exercises/arnold_press.gif',
      muscleAsset: 'assets/muscles/arnold_press.png',
    ),
    ExerciseMeta(
      name: '前平举',
      group: MuscleGroup.shoulders,
      difficulty: '初级',
      equipment: '哑铃/杠铃',
      category: '孤立动作',
      tips: [
      '手臂不要完全伸直',
      '用肩部发力不要借力',
      '慢起慢落',
      ],
      targetMuscles: [
      '三角肌前束',
      ],
      cues: [
      '肘关节微屈',
      '拇指朝上或中立',
      '控制离心下放',
      ],
      imageAsset: 'assets/exercises/lateral_raise.gif',
      muscleAsset: 'assets/muscles/front_raise.png',
    ),
    ExerciseMeta(
      name: '俯身侧平举',
      group: MuscleGroup.shoulders,
      difficulty: '中级',
      equipment: '哑铃',
      category: '孤立动作',
      tips: [
      '手肘微屈',
      '举起时肘部高于手腕',
      '背部保持平直',
      ],
      targetMuscles: [
      '三角肌后束',
      '斜方肌中束',
      ],
      cues: [
      '俯身角度约45度',
      '手臂向两侧打开',
      '顶峰挤压',
      ],
      imageAsset: 'assets/exercises/bent_over_lateral_raise.gif',
      muscleAsset: 'assets/muscles/bent_over_lateral_raise.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Vitruvian-rear-delt-fly-side.mp4',
    ),
    ExerciseMeta(
      name: '侧平举',
      group: MuscleGroup.shoulders,
      difficulty: '初级',
      equipment: '哑铃',
      category: '孤立动作',
      tips: [
      '手臂不要完全伸直',
      '举起至与肩平齐',
      '肘部微屈',
      ],
      targetMuscles: [
      '三角肌中束',
      ],
      cues: [
      '站直，双手各持哑铃置于身体两侧，掌心朝向臀部。',
      '将双臂向两侧抬起，肘部微屈，直到手臂与地面平行。在最高点停顿片刻。',
      '小臂不发力，感受是大臂发力把哑铃给甩起来',
      ],
      imageAsset: 'assets/exercises/lateral_raise.gif',
      muscleAsset: 'assets/muscles/lateral_raise.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Dumbbells-dumbbell-lateral-raise-front.mp4',
    ),
    ExerciseMeta(
      name: '面拉',
      group: MuscleGroup.shoulders,
      difficulty: '初级',
      equipment: '绳索',
      category: '孤立动作',
      tips: [
      '绳索高度与脸平齐',
      '向外拉时旋转手臂',
      '拇指朝上',
      ],
      targetMuscles: [
      '三角肌后束',
      '斜方肌',
      '小圆肌',
      ],
      cues: [
      '向外向后拉',
      '大拇指朝上',
      '肩胛骨向中间夹',
      ],
      imageAsset: 'assets/exercises/face_pull.gif',
      muscleAsset: 'assets/muscles/face_pull.png',
    ),
    ExerciseMeta(
      name: '耸肩',
      group: MuscleGroup.shoulders,
      difficulty: '初级',
      equipment: '哑铃/杠铃',
      category: '孤立动作',
      tips: [
      '垂直上下移动',
      '顶端充分收缩斜方肌',
      '不要前后摆动',
      ],
      targetMuscles: [
      '斜方肌',
      '肩胛提肌',
      ],
      cues: [
      '肩膀向上耸至耳朵高度',
      '顶峰保持1秒',
      '慢下控制',
      ],
      imageAsset: 'assets/exercises/arnold_press.gif',
      muscleAsset: 'assets/muscles/shrug.png',
    ),
    ExerciseMeta(
      name: '二头弯举',
      group: MuscleGroup.arms,
      difficulty: '初级',
      equipment: '哑铃',
      category: '孤立动作',
      tips: [
      '上臂保持固定',
      '顶峰充分收缩',
      '手腕不要晃动',
      ],
      targetMuscles: [
      '肱二头肌',
      '肱肌',
      ],
      cues: [
      '手肘贴近身体两侧',
      '弯举至肩部高度',
      '顶峰挤压',
      ],
      imageAsset: 'assets/exercises/bicep_curl.gif',
      muscleAsset: 'assets/muscles/bicep_curl.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Dumbbells-dumbbell-curl-side.mp4',
    ),
    ExerciseMeta(
      name: '锤式弯举',
      group: MuscleGroup.arms,
      difficulty: '初级',
      equipment: '哑铃',
      category: '孤立动作',
      tips: [
      '手掌相对握哑铃',
      '感受肱肌发力',
      '手腕保持中立',
      ],
      targetMuscles: [
      '肱肌',
      '肱二头肌',
      ],
      cues: [
      '掌心始终相对',
      '垂直上下弯举',
      '顶峰挤压肱肌',
      ],
      imageAsset: 'assets/exercises/hammer_curl.gif',
      muscleAsset: 'assets/muscles/hammer_curl.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Vitruvian-hammer-curl-side.mp4',
    ),
    ExerciseMeta(
      name: '集中弯举',
      group: MuscleGroup.arms,
      difficulty: '初级',
      equipment: '哑铃',
      category: '孤立动作',
      tips: [
      '手肘靠在大腿内侧',
      '控制下放速度',
      '动作全程稳定',
      ],
      targetMuscles: [
      '肱二头肌',
      ],
      cues: [
      '身体略微前倾',
      '弯举时手肘不要外张',
      '感受肌肉拉伸和收缩',
      ],
      imageAsset: 'assets/exercises/bicep_curl.gif',
      muscleAsset: 'assets/muscles/concentration_curl.png',
    ),
    ExerciseMeta(
      name: '杠铃弯举',
      group: MuscleGroup.arms,
      difficulty: '中级',
      equipment: '杠铃',
      category: '孤立动作',
      tips: [
      '握距与肩同宽',
      '不要借助身体晃动发力',
      '顶峰充分收缩',
      ],
      targetMuscles: [
      '肱二头肌',
      '肱肌',
      '前臂肌群',
      ],
      cues: [
      '手臂紧贴身体',
      '弯举至胸前',
      '慢下控制',
      ],
      imageAsset: 'assets/exercises/hammer_curl.gif',
      muscleAsset: 'assets/muscles/barbell_curl.png',
    ),
    ExerciseMeta(
      name: '平板臂屈伸',
      group: MuscleGroup.arms,
      difficulty: '中级',
      equipment: '自重/凳子',
      category: '孤立动作',
      tips: [
      '身体下压时手臂与身体角度要小',
      '三头肌发力撑起',
      '核心收紧',
      ],
      targetMuscles: [
      '肱三头肌',
      ],
      cues: [
      '手臂贴近身体',
      '下降时上臂垂直地面',
      '推起时手臂不完全伸直',
      ],
      imageAsset: 'assets/exercises/push_up.gif',
      muscleAsset: 'assets/muscles/bench_dip.png',
    ),
    ExerciseMeta(
      name: '绳索下压',
      group: MuscleGroup.arms,
      difficulty: '初级',
      equipment: '绳索',
      category: '孤立动作',
      tips: [
      '肘部贴近身体',
      '手腕保持中立',
      '集中三头肌发力',
      ],
      targetMuscles: [
      '肱三头肌',
      ],
      cues: [
      '大臂始终垂直',
      '向下压直到手臂伸直',
      '顶峰收缩',
      ],
      imageAsset: 'assets/exercises/push_up.gif',
      muscleAsset: 'assets/muscles/tricep_pushdown.png',
    ),
    ExerciseMeta(
      name: '过头臂屈伸',
      group: MuscleGroup.arms,
      difficulty: '初级',
      equipment: '哑铃',
      category: '孤立动作',
      tips: [
      '双手捧哑铃置于脑后',
      '大臂保持紧贴头部两侧',
      '肘部不要外张',
      ],
      targetMuscles: [
      '肱三头肌',
      ],
      cues: [
      '大臂保持不动',
      '前臂上下移动',
      '控制动作速度',
      ],
      imageAsset: 'assets/exercises/arnold_press.gif',
      muscleAsset: 'assets/muscles/overhead_extension.png',
    ),
    ExerciseMeta(
      name: '深蹲',
      group: MuscleGroup.legs,
      difficulty: '中级',
      equipment: '杠铃/自重',
      category: '复合动作',
      tips: [
      '膝盖与脚尖方向一致',
      '下蹲深度大腿与地面平行',
      '核心收紧',
      ],
      targetMuscles: [
      '股四头肌',
      '臀肌',
      '腘绳肌',
      '核心',
      ],
      cues: [
      '挺胸收紧下背部',
      '膝盖向外撑开',
      '重心在脚后跟',
      ],
      imageAsset: 'assets/exercises/romanian_deadlift.gif',
      muscleAsset: 'assets/muscles/squat.png',
    ),
    ExerciseMeta(
      name: '硬拉',
      group: MuscleGroup.legs,
      difficulty: '中级',
      equipment: '杠铃',
      category: '复合动作',
      tips: [
      '背部挺直不要弓背',
      '杠铃贴近身体移动',
      '膝盖与脚尖同向',
      ],
      targetMuscles: [
      '腘绳肌',
      '臀肌',
      '下背部',
      '股四头肌',
      ],
      cues: [
      '杠铃全程贴近小腿',
      '臀部向后送',
      '发力时呼气',
      ],
      imageAsset: 'assets/exercises/romanian_deadlift.gif',
      muscleAsset: 'assets/muscles/deadlift.png',
    ),
    ExerciseMeta(
      name: '直腿硬拉',
      group: MuscleGroup.legs,
      difficulty: '中级',
      equipment: '杠铃/哑铃',
      category: '复合动作',
      tips: [
      '膝盖保持微曲',
      '感受腘绳肌拉伸',
      '背部平直不弓背',
      ],
      targetMuscles: [
      '腘绳肌',
      '臀肌',
      '下背部',
      ],
      cues: [
      '杠铃贴着腿部上下',
      '臀部向后撅',
      '感受大腿后侧拉伸',
      ],
      imageAsset: 'assets/exercises/romanian_deadlift.gif',
      muscleAsset: 'assets/muscles/rdl.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Vitruvian-romanian-deadlift-side.mp4',
    ),
    ExerciseMeta(
      name: '腿举',
      group: MuscleGroup.legs,
      difficulty: '初级',
      equipment: '器械',
      category: '复合动作',
      tips: [
      '脚间距与肩同宽',
      '下降时膝盖不要内扣',
      '下放深度要适中',
      ],
      targetMuscles: [
      '股四头肌',
      '臀肌',
      ],
      cues: [
      '脚尖朝前或微外八',
      '膝盖不要超伸',
      '保持核心收紧',
      ],
      imageAsset: 'assets/exercises/romanian_deadlift.gif',
      muscleAsset: 'assets/muscles/leg_press.png',
    ),
    ExerciseMeta(
      name: '腿弯举',
      group: MuscleGroup.legs,
      difficulty: '初级',
      equipment: '器械',
      category: '孤立动作',
      tips: [
      '慢下快起',
      '充分收缩腘绳肌',
      '膝盖始终贴合垫子',
      ],
      targetMuscles: [
      '腘绳肌',
      ],
      cues: [
      '大臂贴合垫子',
      '弯举至最高点',
      '控制离心下放',
      ],
      imageAsset: 'assets/exercises/romanian_deadlift.gif',
      muscleAsset: 'assets/muscles/leg_curl.png',
    ),
    ExerciseMeta(
      name: '腿伸展',
      group: MuscleGroup.legs,
      difficulty: '初级',
      equipment: '器械',
      category: '孤立动作',
      tips: [
      '单侧做完换另一侧',
      '感受大腿前侧发力',
      '膝盖不要超伸',
      ],
      targetMuscles: [
      '股四头肌',
      ],
      cues: [
      '背部紧贴靠垫',
      '脚尖向上勾起',
      '顶峰收缩1秒',
      ],
      imageAsset: 'assets/exercises/romanian_deadlift.gif',
      muscleAsset: 'assets/muscles/leg_extension.png',
    ),
    ExerciseMeta(
      name: '保加利亚深蹲',
      group: MuscleGroup.legs,
      difficulty: '中级',
      equipment: '哑铃/自重',
      category: '复合动作',
      tips: [
      '后脚放在凳子上',
      '前膝不超过脚尖',
      '躯干保持直立',
      ],
      targetMuscles: [
      '股四头肌',
      '臀肌',
      '腘绳肌',
      ],
      cues: [
      '后脚高度略低于前脚',
      '前蹲深度大腿与地面平行',
      '重心在前脚脚后跟',
      ],
      imageAsset: 'assets/exercises/romanian_deadlift.gif',
      muscleAsset: 'assets/muscles/bulgarian_split.png',
    ),
    ExerciseMeta(
      name: '臀桥',
      group: MuscleGroup.glutes,
      difficulty: '初级',
      equipment: '自重/杠铃',
      category: '孤立动作',
      tips: [
      '脚跟发力，不要用腰顶',
      '顶峰停顿1-2秒感受臀部收缩',
      '下巴微收，肋骨不要外翻',
      ],
      targetMuscles: [
      '臀大肌',
      '腘绳肌',
      '核心',
      ],
      cues: [
      '仰卧屈膝，脚掌踩实地面，脚跟靠近臀部',
      '收紧核心后向上抬髋，直到肩-髋-膝接近一条直线',
      '下放时控制速度，不要直接砸回地面',
      ],
      imageAsset: 'assets/exercises/romanian_deadlift.gif',
      muscleAsset: 'assets/muscles/glute_bridge.png',
    ),
    ExerciseMeta(
      name: '杠铃臀推',
      group: MuscleGroup.glutes,
      difficulty: '中级',
      equipment: '杠铃',
      category: '复合动作',
      tips: [
      '上背稳定靠在凳边',
      '顶峰骨盆后倾，避免腰椎代偿',
      '膝盖方向与脚尖一致',
      ],
      targetMuscles: [
      '臀大肌',
      '臀中肌',
      '腘绳肌',
      ],
      cues: [
      '肩胛下缘靠凳，杠铃放在髋部，双脚与肩同宽',
      '脚跟发力向上顶髋，到顶时小腿尽量垂直地面',
      '缓慢下放至臀部接近地面，再开始下一次',
      ],
      imageAsset: 'assets/exercises/romanian_deadlift.gif',
      muscleAsset: 'assets/muscles/hip_thrust.png',
    ),
    ExerciseMeta(
      name: '保加利亚深蹲（臀部主导）',
      group: MuscleGroup.glutes,
      difficulty: '中级',
      equipment: '哑铃/自重',
      category: '复合动作',
      tips: [
      '步距拉大一点，更容易吃到臀',
      '身体微微前倾但背部保持平直',
      '前脚脚跟踩稳，避免前脚掌抢力',
      ],
      targetMuscles: [
      '臀大肌',
      '臀中肌',
      '股四头肌',
      ],
      cues: [
      '后脚放在凳子上，前脚向前迈出足够距离',
      '下蹲时让重心落在前脚脚跟和足中',
      '起身时想象用臀部把身体顶起来',
      ],
      imageAsset: 'assets/exercises/romanian_deadlift.gif',
      muscleAsset: 'assets/muscles/bulgarian_split_glute.png',
    ),
    ExerciseMeta(
      name: '罗马尼亚硬拉（臀部主导）',
      group: MuscleGroup.glutes,
      difficulty: '中级',
      equipment: '杠铃/哑铃',
      category: '复合动作',
      tips: [
      '全程保持脊柱中立',
      '重心放在脚中后部',
      '下降到臀腿后侧有明显拉伸即可',
      ],
      targetMuscles: [
      '臀大肌',
      '腘绳肌',
      '下背部',
      ],
      cues: [
      '微屈膝后先主动向后送臀，而不是低头弯腰',
      '器械贴近腿部下滑，肩膀和髋部一起移动',
      '起身时夹紧臀部，把髋向前推回中立位',
      ],
      imageAsset: 'assets/exercises/romanian_deadlift.gif',
      muscleAsset: 'assets/muscles/rdl_glute.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Vitruvian-romanian-deadlift-side.mp4',
    ),
    ExerciseMeta(
      name: '绳索后踢腿',
      group: MuscleGroup.glutes,
      difficulty: '初级',
      equipment: '绳索',
      category: '孤立动作',
      tips: [
      '动作幅度不用太大，重点是臀部收缩',
      '骨盆保持稳定，不要左右晃',
      '回程慢一点，保持持续张力',
      ],
      targetMuscles: [
      '臀大肌',
      '臀中肌',
      ],
      cues: [
      '身体微前倾扶稳支撑物，训练腿微屈膝',
      '向后上方踢腿，注意不是甩腿',
      '顶峰停顿一下，再控制回到起点',
      ],
      imageAsset: 'assets/exercises/face_pull.gif',
      muscleAsset: 'assets/muscles/cable_kickback.png',
    ),
    ExerciseMeta(
      name: '蚌式开合',
      group: MuscleGroup.glutes,
      difficulty: '初级',
      equipment: '自重/弹力带',
      category: '孤立动作',
      tips: [
      '双脚始终并拢',
      '骨盆不要后仰',
      '动作小而稳，重点找臀中肌发力',
      ],
      targetMuscles: [
      '臀中肌',
      '臀小肌',
      ],
      cues: [
      '侧卧屈膝约90度，髋部叠放稳定',
      '保持脚跟贴合，仅抬起上侧膝盖',
      '打开到极限后停顿，再缓慢合上',
      ],
      imageAsset: 'assets/exercises/plank.gif',
      muscleAsset: 'assets/muscles/clamshell.png',
    ),
    ExerciseMeta(
      name: '卷腹',
      group: MuscleGroup.core,
      difficulty: '初级',
      equipment: '自重',
      category: '孤立动作',
      tips: [
      '下背部始终贴地',
      '用腹肌发力不要用手部',
      '不要按住头部',
      ],
      targetMuscles: [
      '腹直肌',
      ],
      cues: [
      '卷起时呼气',
      '肩膀离地即可不要完全坐起',
      '慢下快起',
      ],
      imageAsset: 'assets/exercises/bicycle_crunch.gif',
      muscleAsset: 'assets/muscles/crunch.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Vitruvian-crunch-side.mp4',
    ),
    ExerciseMeta(
      name: '平板支撑',
      group: MuscleGroup.core,
      difficulty: '初级',
      equipment: '自重',
      category: '核心稳定',
      tips: [
      '身体保持一条直线',
      '不要塌腰或撅臀',
      '肩膀在肘部正上方',
      ],
      targetMuscles: [
      '腹横肌',
      '腹直肌',
      '斜方肌',
      '臀部',
      ],
      cues: [
      '腹部收紧',
      '均匀呼吸',
      '保持30-60秒',
      ],
      imageAsset: 'assets/exercises/plank.gif',
      muscleAsset: 'assets/muscles/plank.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Medicine-Ball-plank-side.mp4',
    ),
    ExerciseMeta(
      name: '俄罗斯转体',
      group: MuscleGroup.core,
      difficulty: '初级',
      equipment: '药球/徒手',
      category: '旋转动作',
      tips: [
      '脚离地增加难度',
      '转向时感受侧腹发力',
      '动作要连贯',
      ],
      targetMuscles: [
      '腹斜肌',
      '腹直肌',
      ],
      cues: [
      '身体呈V型',
      '双手在胸前交叉',
      '左右旋转躯干',
      ],
      imageAsset: 'assets/exercises/russian_twist.gif',
      muscleAsset: 'assets/muscles/russian_twist.png',
      videoUrl: 'https://media.musclewiki.com/media/uploads/videos/branded/female-Medicine-Ball-russian-twist-side.mp4',
    ),
    ExerciseMeta(
      name: '自行车卷腹',
      group: MuscleGroup.core,
      difficulty: '初级',
      equipment: '自重',
      category: '孤立动作',
      tips: [
      '动作要缓慢控制',
      '对侧手肘触碰膝盖',
      '下背部始终贴地',
      ],
      targetMuscles: [
      '腹直肌',
      '腹斜肌',
      ],
      cues: [
      '交替进行',
      '膝盖弯曲呈90度',
      '感受腹肌发力',
      ],
      imageAsset: 'assets/exercises/bicycle_crunch.gif',
      muscleAsset: 'assets/muscles/bicycle_crunch.png',
    ),
    ExerciseMeta(
      name: '死虫式',
      group: MuscleGroup.core,
      difficulty: '中级',
      equipment: '自重',
      category: '核心稳定',
      tips: [
      '下背部全程贴地',
      '手脚交替时身体不旋转',
      '动作要缓慢',
      ],
      targetMuscles: [
      '腹横肌',
      '腹直肌',
      '臀肌',
      ],
      cues: [
      '手臂垂直地面上下移动',
      '腿与地面呈90度',
      '腰部紧贴地面',
      ],
      imageAsset: 'assets/exercises/plank.gif',
      muscleAsset: 'assets/muscles/dead_bug.png',
    ),
    ExerciseMeta(
      name: '鸟狗式',
      group: MuscleGroup.core,
      difficulty: '中级',
      equipment: '自重',
      category: '核心稳定',
      tips: [
      '支撑臂垂直地面',
      '伸展时身体保持稳定',
      '头部与脊柱成一条线',
      ],
      targetMuscles: [
      '竖脊肌',
      '臀肌',
      '腹横肌',
      ],
      cues: [
      '手臂和对侧腿同时伸出',
      '收紧核心',
      '保持身体平衡',
      ],
      imageAsset: 'assets/exercises/plank.gif',
      muscleAsset: 'assets/muscles/bird_dog.png',
    ),
    ExerciseMeta(
      name: '悬垂举腿',
      group: MuscleGroup.core,
      difficulty: '中级',
      equipment: '单杠',
      category: '孤立动作',
      tips: [
      '双腿并拢伸直',
      '抬起时不要借助惯性',
      '控制下放速度',
      ],
      targetMuscles: [
      '腹直肌',
      '腹斜肌',
      '髂腰肌',
      ],
      cues: [
      '骨盆微微后倾',
      '抬腿至与地面平行或更高',
      '慢下控制',
      ],
      imageAsset: 'assets/exercises/plank.gif',
      muscleAsset: 'assets/muscles/hanging_leg_raise.png',
    ),
  ];

  static List<ExerciseMeta> getMetasForGroup(MuscleGroup group) {
    return exercises.where((e) => e.group == group).toList();
  }

  static List<ExerciseMeta> search(String query) {
    final q = query.toLowerCase();
    return exercises.where((e) =>
      e.name.toLowerCase().contains(q) ||
      e.equipment.toLowerCase().contains(q) ||
      e.category.toLowerCase().contains(q) ||
      e.targetMuscles.any((m) => m.toLowerCase().contains(q))
    ).toList();
  }
}
